export const TABLE_NAME_PRODUCT = 'cat__product'
export const TABLE_NAME_PRODUCT_SPECIFICATION = 'cat__product_specification'
export const TABLE_NAME_PRODUCT_FILTER_VALUE = 'cat__product_filter_value'
export const TABLE_NAME_PRODUCT_CATEGORY = 'cat__product_category'
export const TABLE_NAME_PRODUCT_FILES = 'cat__product_files'
export const TABLE_NAME_BROKEN_LINK = 'cat__broken_link'
export const TABLE_NAME_CATEGORY = 'cat__category'
export const TABLE_NAME_SPECIFICATION = 'cat__specification'
export const TABLE_NAME_FILTER = 'cat__filter'
export const TABLE_NAME_FILTER_VALUE = 'cat__filter_value'
export const TABLE_NAME_DISCOUNT_GROUPS = 'cat__discount_group'
export const TABLE_NAME_CATALOG = 'cat__catalog'
export const TABLE_NAME_CATEGORY_CONNECTED = 'cat__category_connected'
export const TABLE_NAME_FILTER_CONNECTED = 'cat__filter_connected'

export const IDX_TABLE_GROUP = 'cat__product_idx_group'
export const IDX_TABLE_GROUP_CATEGORY = 'cat__product_idx_group_category'
export const IDX_TABLE_GROUP_FILTERS = 'cat__product_idx_group_filter_all'
export const IDX_TABLE_PRODUCT = 'cat__product_idx_product'
export const IDX_TABLE_PRODUCT_CATEGORY = 'cat__product_idx_product_category'
export const IDX_TABLE_PRODUCT_FILTERS = 'cat__product_idx_product_filter_all'
export const IDX_TABLE_NAMES = [IDX_TABLE_GROUP, IDX_TABLE_GROUP_CATEGORY, IDX_TABLE_GROUP_FILTERS, IDX_TABLE_PRODUCT, IDX_TABLE_PRODUCT_CATEGORY, IDX_TABLE_PRODUCT_FILTERS]

export const TABLE_NAME_CACHE_PRODUCT = 'cat__product_cache'
export const TABLE_NAME_CACHE_STOCK_AND_PRICES = 'cat__stock_and_prices_cache'
