export enum CatSpecificationType {
  url = 'url',
  size = 'size',
  // clothesSize = 'clothes-size',
  material = 'material',
  brand = 'brand',
  weight = 'weight',
  colors = 'colors',
  packAmount = 'pack-amount',
  packWeight = 'pack-weight',
  packVolume = 'pack-volume',
  packSizes = 'pack-sizes',
  packSizeX = 'pack-size-X',
  packSizeY = 'pack-size-Y',
  packSizeZ = 'pack-size-Z',
  volume = 'volume',
  length = 'length',
  width = 'width',
  // vendor = 'vendor',
  // groupName = 'group-name',
  articleBase = 'article-base',
  originalName = 'original-name',
  shortName = 'short-name',
  printJson = 'printJson'
}